import { GradingSessionDetailResponse } from "./api";
/*
 * Route: /grader/session/<int:pk/
 */
export const gradingSessionDetail: GradingSessionDetailResponse = {
  session: {
    pk: 2,
    api_assignment_id: "319837130648",
    max_grade: 75,
    teacher_template: "",
    submissions: [
      {
        pk: 3,
        api_student_profile_id: "104478187393448600976",
        api_student_submission_id: "Cg0IlcG081QQmJ-dvqcJ",
        submission: [
          "Jack DeVries - This is attachment three",
          "=======================================",
          "This is attachment three",
          "And it is a google slide",
          "How about that?",
          "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
          "What do you think?",
          "Your answer:",
          "_____great stuff____",
          "Jack DeVries - Attachment One",
          "=============================",
          "﻿This is attachment one?",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their thicc default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
          "Jack DeVries - Attachment Two",
          "=============================",
          "﻿This is attachment two.",
          "",
          "",
          "Where can I get some more?",
          "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
          "1800x1200_is_my_cat_normal_slideshow.jpg",
          "========================================",
          "1800x1200_is_my_cat_normal_slideshow.jpg could not be imported because it is not from a GSuite program like Google Docs, Google Slides, etc.",
        ],
        student_name: "Jack DeVries",
        grade: 58,
        comment: "Nice",
      },
      {
        pk: 4,
        api_student_profile_id: "100316609354151322799",
        api_student_submission_id: "Cg4IzILhqI0LEJifnb6nCQ",
        submission: [
          "Jack DeVries - This is attachment three",
          "=======================================",
          "This is attachment three",
          "And it is a google slide",
          "How about that?",
          "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
          "What do you think?",
          "Your answer:",
          "____awful_____",
          "Jack DeVries - Attachment One",
          "=============================",
          "﻿This is attachment one?",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and song a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
          "Jack DeVries - Attachment Two",
          "=============================",
          "﻿This is attachment two.",
          "",
          "",
          "Where can I get some?",
          "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything stupendous embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
        ],
        student_name: "Jack DeVries",
        grade: 66,
        comment: "cool",
      },
    ],
    average_grade: 62,
    google_classroom_detail_view_url:
      "https://classroom.google.com/c/MzgxNTMyMDA3ODU5/a/MzE5ODM3MTMwNjQ4/submissions/by-status/and-sort-first-name/all",
  },
};
